# Indexing

In [3]:
import numpy as np


In [7]:
a = np.array([9,8,7,6])
print(a)

[9 8 7 6]


In [10]:
print(a[-1],a[-2],a[-3],a[-4])

6 7 8 9


In [19]:
twoD = np.array([[9,8,7],[4,5,6]])
print(twoD)
#check dim of the 2d array 
print(twoD.ndim)
# 1st row 3rd column
print(twoD[0,2])

[[9 8 7]
 [4 5 6]]
2
7


In [26]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[21,22,23],[24,25,26],[27,28,29]]])
print(threeD,'dimension: ',threeD.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] dimension:  3


In [27]:
print(threeD[1,1,2])

26
